# Generated by Django 2.2.4 on 2019-08-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=30, verbose_name='Contact email')),
                ('message', models.TextField()),
            ],
        ),
    ]
