# Generated by Django 2.2.4 on 2019-09-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190806_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='to',
            field=models.EmailField(default='asa@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
